#!/bin/bash

set -e

# Start in project root
cd $(dirname "$0")/..

source tools/common.bash
source tools/source-maps

# Copy/patch Eta.PackageDb
patch_source \
  "eta/libraries/eta-boot/Eta/PackageDb.hs" \
  "gen/src/Language/Eta/PackageDb.hs" \
  "patches/Language/Eta/PackageDb.hs.patch"

# Copy/patch modules
for src in "${sources[@]}"; do
  patch_source \
    "eta/compiler/ETA/$src.hs" \
    "gen/src/Language/Eta/$src.hs" \
    "patches/Language/Eta/$src.hs.patch"
done

# Copy/patch boot sources
for src in "${boot_sources[@]}"; do
  patch_source \
    "eta/compiler/ETA/$src.hs-boot" \
    "gen/src/Language/Eta/$src.hs-boot" \
    "patches/Language/Eta/$src.hs-boot.patch"
done

# Copy/patch codec-jvm sources
for src in "${codec_jvm[@]}"; do
  patch_source \
    "eta/codec-jvm/src/$src.hs" \
    "gen/src/$src.hs" \
    "patches/$src.hs.patch"
done
