#!/bin/bash

# Validates hpack to ensure we have the right version, then executes it.

min_required_version=0.24.0

failed() {
  >&2 printf "hpack >= 0.24.0 is required"
  [ -z "$current_version" ] || >&2 printf " but found $current_version"
  >&2 echo
  exit 1
}

command -v hpack > /dev/null || failed

current_version=$(hpack --numeric-version)

vsort() {
  # OSX doesn't have sort -V, so we need to hack our own
  # Adapted from https://stackoverflow.com/a/21395280/1313611
  printf '%s\n%s\n' "$1" "$2" \
    | sed 's/\b\([0-9]\)\b/0\1/g' | sort | sed 's/\b0\([0-9]\)/\1/g'
}

if [ "$current_version" != "$min_required_version" ]; then
  top_version=$(vsort "$min_required_version" "$current_version" | head -n1)
  [ "$top_version" == "$min_required_version" ] || failed
fi

exec hpack "$@"
